"""Linear and nonlinear solver kernels."""

from remec.options import CurrentContinuityStabilization
from remec.solvers.anisotropic_diffusion import (
    AnisotropicDiffusionResult,
    AnisotropicDiffusionSolver,
    AnisotropyPollutionError,
    AnisotropyPollutionWarning,
    EnergyDiagnostics,
    FloorSensitivityDiagnostic,
    FloorSensitivityError,
    FloorSensitivityWarning,
    PollutionSafetyDiagnostic,
    SpatialAnisotropicConductivity,
)
from remec.solvers.axisymmetric import (
    AxisymmetricGradShafranovCoefficients,
    AxisymmetricGradShafranovResult,
    AxisymmetricGradShafranovSolver,
    AxisymmetricProfileClosure,
    AxisymmetricProfileClosureEvaluation,
)
from remec.solvers.continuation import (
    ContinuationAcceptanceError,
    ContinuationStage,
    ContinuationStageResult,
    StagedContinuationOptions,
    StagedContinuationResult,
    StagedContinuationSolver,
)
from remec.solvers.current_continuity import (
    ConstrainedCurrentContinuityResult,
    ConstrainedCurrentContinuitySolver,
    CurrentContinuityFormulation,
    CurrentContinuityResult,
    CurrentContinuitySolver,
    CurrentLayerResolutionDiagnostic,
    FrozenCurrentConstraintGeometry,
    FrozenCurrentContinuityCoefficients,
    UnresolvedCurrentLayerError,
    UnresolvedCurrentLayerWarning,
)
from remec.solvers.picard import DampedPicardSolver, PicardOptions

__all__ = [
    "AnisotropicDiffusionResult",
    "AnisotropicDiffusionSolver",
    "AnisotropyPollutionError",
    "AnisotropyPollutionWarning",
    "AxisymmetricGradShafranovCoefficients",
    "AxisymmetricGradShafranovResult",
    "AxisymmetricGradShafranovSolver",
    "AxisymmetricProfileClosure",
    "AxisymmetricProfileClosureEvaluation",
    "ConstrainedCurrentContinuityResult",
    "ConstrainedCurrentContinuitySolver",
    "ContinuationAcceptanceError",
    "ContinuationStage",
    "ContinuationStageResult",
    "CurrentContinuityFormulation",
    "CurrentContinuityResult",
    "CurrentContinuitySolver",
    "CurrentContinuityStabilization",
    "CurrentLayerResolutionDiagnostic",
    "DampedPicardSolver",
    "EnergyDiagnostics",
    "FloorSensitivityDiagnostic",
    "FloorSensitivityError",
    "FloorSensitivityWarning",
    "FrozenCurrentConstraintGeometry",
    "FrozenCurrentContinuityCoefficients",
    "PicardOptions",
    "PollutionSafetyDiagnostic",
    "SpatialAnisotropicConductivity",
    "StagedContinuationOptions",
    "StagedContinuationResult",
    "StagedContinuationSolver",
    "UnresolvedCurrentLayerError",
    "UnresolvedCurrentLayerWarning",
]
